#!/bin/bash

source /usr/local/ntlm-auth-api/containers/systemd-service

name=ntlm-join-remote

args=`base_args $name`
args="$args -p 127.0.0.1:8080:8080"

run $name "$args" "/usr/local/pf/sbin/ntlm-join-remote"
